Cci photogram industrial 2
Cindellai/photogram-industrial pull request #2
Opened 2024-07-02 19:32 UTC by Cindellai

2024-07-02 20:07 UTC, SaraDawner2000 requested changes
Looks great!
In the comment model, I think you should add the counter_cache: true function to the belongs_to: :photos association, because we have a "comment_count" column in the Photos table

2024-07-02 20:07 UTC, SaraDawner2000 commented on app/models/comment.rb
> +  belongs_to :photo
needs to have :counter_cache: true because Photos table has comments_count column

2024-07-02 20:07 UTC, SaraDawner2000 commented on app/views/comments/_comment.html.erb
I see you got started on the frontend?

2024-07-02 20:07 UTC, SaraDawner2000 commented on config/routes.rb
> +   root "photos#index"
nice catch lol, I would've forgotten to fix this

2024-07-02 20:07 UTC, SaraDawner2000 commented on lib/tasks/dev.rake
> +      next if first_user == second_user
neat catch, I forgot this!

2024-07-02 20:07 UTC, SaraDawner2000 commented on lib/tasks/dev.rake
> +      user.followers.each do |follower|
love the way you added likes!

2024-07-02 20:13 UTC, Cindellai commented on app/models/comment.rb
> +  belongs_to :photo
added countercache for photos

2024-07-02 20:14 UTC, SaraDawner2000 approved these changes
great!

2024-07-02 20:29 UTC, thierrychau requested changes
Great job overall, I have some minor comments below. Let me know when you have made the changes, and leave the conversation unresolved for me to resolve. Thanks!

2024-07-02 20:29 UTC, thierrychau commented on Gemfile
> +  gem 'annotate'
It's already in there, line 94

2024-07-02 20:29 UTC, thierrychau commented on app/models/like.rb
> +  validates :fan_id, uniqueness: { scope: :photo_id, message: "has already liked this photo" }
Great job!

2024-07-02 20:29 UTC, thierrychau commented on config/initializers/simple_form.rb
Do we need simple form?

2024-07-02 20:53 UTC, Cindellai commented on config/initializers/simple_form.rb
the file should be gone now, thank you!

2024-07-02 21:01 UTC, thierrychau commented on Gemfile
> +  gem 'annotate'
@Cindellai up in case you didn't see this comment

2024-07-03 13:14 UTC, thierrychau commented
Hi @Cindellai, can you just fix the gemfile really quick before I can approve your PR? Thanks

2024-07-03 16:23 UTC, thierrychau approved these changes
Great job, good to merge!

2024-07-03 16:59 UTC, merged